# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyShoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(choices=[('addidas', 'Addidas'), ('nike', 'Nike'), ('new balance', 'New Balance'), ('Asics', 'Asics'), ('Brooks', 'Brooks'), ('Under Armour', 'Under Armour')], default='addidas', max_length=30)),
                ('icon', models.CharField(choices=[('running_shoe.png', 'Running Shoe'), ('running_spike.png', 'Running Spike'), ('competition_running_shoe.png', 'Competition Running Shoe')], default='running_shoe.png', max_length=30)),
                ('miles_run', models.IntegerField(default=0)),
            ],
        ),
    ]
