# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('happyfeet', '0003_auto_20170803_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshoe',
            name='shoe_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
