# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyfeet', '0005_auto_20170804_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myshoe',
            old_name='shoe_id',
            new_name='ID',
        ),
    ]
