# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyfeet', '0006_auto_20170804_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myshoe',
            old_name='ID',
            new_name='shoe_id',
        ),
    ]
