# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyfeet', '0008_auto_20170804_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshoe',
            name='shoe_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
