# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyfeet', '0009_auto_20170804_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myshoe',
            name='shoe_id',
        ),
        migrations.AddField(
            model_name='myshoe',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
